In [39]:
import math as mt

In [2]:
mt.sqrt(25)

5.0

In [4]:
mt.pi

3.141592653589793

In [5]:
import numpy as np

In [6]:
from numpy import random

In [7]:
import numpy as np

In [13]:
# uniform random numbers in [0,1]
dataOne = random.rand(5,5)

In [14]:
dataOne

array([[0.25964415, 0.29979403, 0.07185557, 0.50255081, 0.97673272],
       [0.23152441, 0.23942028, 0.1393433 , 0.48526504, 0.61370433],
       [0.91397279, 0.71820543, 0.90688785, 0.76117953, 0.64394904],
       [0.9609539 , 0.62833968, 0.16453212, 0.21845723, 0.64806691],
       [0.01650345, 0.1098465 , 0.43599059, 0.03796768, 0.8245777 ]])

In [10]:
np.mean(dataOne)

0.5923472349425779

# Now it is your turn! Use three predefined functions with math and stats to obtain information about the data stored in the numpy array; note any issues you encounter along the way as comments in your notebook. These will serve you well later as lesson learned that you have documented and can reference.

In [12]:
from scipy import stats
import math as mt

In [32]:
a=dataOne

In [47]:
#Returns the modal value
m=stats.mode(a)
print(m)
print(m[0])

ModeResult(mode=array([[0.01650345, 0.1098465 , 0.07185557, 0.03796768, 0.61370433]]), count=array([[1, 1, 1, 1, 1]]))
[[0.01650345 0.1098465  0.07185557 0.03796768 0.61370433]]


In [43]:
#Computes several descriptive statistics of the passed array
stats.describe(a)

DescribeResult(nobs=5, minmax=(array([0.01650345, 0.1098465 , 0.07185557, 0.03796768, 0.61370433]), array([0.9609539 , 0.71820543, 0.90688785, 0.76117953, 0.97673272])), mean=array([0.47651974, 0.39912118, 0.34372189, 0.40108406, 0.74140614]), variance=array([0.18617859, 0.0683515 , 0.11836507, 0.07806419, 0.02420349]), skewness=array([ 0.26146131,  0.23886458,  0.99532428, -0.07221119,  0.72641533]), kurtosis=array([-1.71718601, -1.60356475, -0.57100423, -1.18121114, -1.1080133 ]))

In [44]:
#Computes geometric mean along the specified axis
stats.gmean(a)

array([0.24436398, 0.32377451, 0.23055024, 0.2738327 , 0.7292687 ])

In [48]:
#Calculates the z score of each value in the sample, relative to the sample mean and standard deviation
stats.zscore(a)

array([[-0.56195407, -0.42476525, -0.88348387,  0.40602506,  1.69116896],
       [-0.63481613, -0.68294915, -0.66416903,  0.33685505, -0.91772607],
       [ 1.13350017,  1.36454026,  1.83012023,  1.44094282, -0.70037315],
       [ 1.2552346 ,  0.98023603, -0.58231291, -0.7307918 , -0.67078019],
       [-1.19196458, -1.2370619 ,  0.29984558, -1.45303113,  0.59771045]])

In [76]:
a1=dataOne[0]
print("sin(a1) = \n", [mt.sin(x) for x in a1])

sin(a1) = 
 [0.2567366428641366, 0.29532343182702436, 0.07179375240363545, 0.4816625207047228, 0.8286729922394075]


AttributeError: module 'math' has no attribute 'mean'

In [54]:
functionname()

NameError: name 'functionname' is not defined

In [55]:
print('I Love Data Science')

I Love Data Science


In [56]:
variablename =25

In [57]:
variableName1= 'I Love Data Science'

In [58]:
print(variablename)
print(variableName1)

25
I Love Data Science


In [60]:
type(variablename)

int

In [61]:
type(variableName1)

str

In [67]:
variablename =25.0
type(variablename)

float

In [68]:
varOne=25

In [69]:
varTwo = 25.0

In [70]:
varThree = varOne + varTwo
print(varThree)

50.0


In [73]:
varTwo= 'Hello'

In [81]:
varThree = varOne + varTwo
print(varThree)

#TypeError: unsupported operand type(s) for +: 'int' and 'str'
#https://pythonspot.com/datatype-casting/

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [83]:
#TypeError: unsupported operand type(s) for +: 'int' and 'str'
# print only accepts the string datatype.
##Refer to this page for more info on Datatype casting
# https://pythonspot.com/datatype-casting/
#https://www.geeksforgeeks.org/type-conversion-python/

varThree = str(varOne) + varTwo
print(varThree)

25Hello


In [ ]:
listName = []

In [85]:
listOne = [1,2,3,4]
#The numbers in the brackets are called elements. Each element can be of any type and can be referenced by their index

In [86]:
print(listOne[1:3])
#This returns the second and third element in the list [2 ,3]; note that the indexes begin at 0 so [0:2] will return [1, 2]

[2, 3]


In [87]:
tel = {'jack': 4098, 'sape': 4139}

In [88]:
tel['jack']

4098

In [105]:
#Define a variable that represents a dictionary with 5 INT elements
fivint = {'vj': 237, 'rv': 203, 'sr' : 405, 'joe' :101 ,'jess': 0}

In [90]:
fivint['vj']

237

# Use functions from the math module to perform three different math operations on three of the five elements; you may find it easier to define variables for the elements. Feel free to combine elements as needed. #Lastly, print out you results separately.


In [106]:
vj=fivint['vj']
rv =fivint['rv']
sr=fivint['sr']
joe=fivint['joe']
jess=fivint['jess']

In [111]:
mt.fabs(vj)
#Return the absolute value of x.

237.0

In [108]:
mt.trunc(vj)
#Return the Real value x truncated to an Integral (usually an integer).

237

In [109]:
mt.isfinite(vj)
#Return True if x is neither an infinity nor a NaN, and False otherwise. (Note that 0.0 is considered finite.)

True

In [110]:
mt.factorial(vj)
#Return x factorial.

297976905673664935047816526719560179419093566446241572177911873782676338657629325036120150027567927385041320207173776316112533845790828129808740140341588672218544752564381505087410826234304248359063246670539274917998749482684890734236332214086176076308821914543172491163329091874698705047455860455252985775559487256924098658333601938809292553392248924659865897822485158978199509626479821986381518730166272000000000000000000000000000000000000000000000000000000000

In [112]:
mt.trunc(sr)
#Return the Real value x truncated to an Integral (usually an integer).

405

In [113]:
mt.isfinite(sr)
#Return True if x is neither an infinity nor a NaN, and False otherwise. (Note that 0.0 is considered finite.)

True

In [114]:
mt.factorial(sr)
#Return x factorial.

680653430795508222449215242344688836073772491351993243108104021529172862296618381671146763288197909957987968655945984203282734249489713804927338956555174337630247550281760920826142162578635607580071998286010058821506749545567724090026130884819510677024442778521339972820054862416684684727562940219165453539811395785181379143617266753639486247164299169997093333186300366570950105712514667409176782891454358338435635561336438008820107692077791906804482678565592846760727615700936666392463771968231848050393624243116362681216952269743662286334246519620571045875191829388523307795334877258281501232741715196988134164879819386274040667891134790080117596714717431878335432959042050183867570825629458143442813382995883283677184758453052929044905714920488418950338331979495316873916721397760000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

In [115]:
mt.trunc(joe)
#Return the Real value x truncated to an Integral (usually an integer).

101

In [116]:
mt.isfinite(joe)
#Return True if x is neither an infinity nor a NaN, and False otherwise. (Note that 0.0 is considered finite.)

True

In [117]:
mt.factorial(joe)
#Return x factorial.

9425947759838359420851623124482936749562312794702543768327889353416977599316221476503087861591808346911623490003549599583369706302603264000000000000000000000000